language: go
go:
  - 1.5.2
  - 1.5.3
sudo: false

install:
    - go get -u github.com/golang/lint/golint
    - go get -u github.com/spf13/cobra
    - go get -u github.com/spf13/viper
    - go get -u github.com/google/go-github/github
    - go get -u golang.org/x/oauth2

script:
    - test -z "$(golint github.com/ifosch/one2merge/one2merge)"
    - golint github.com/ifosch/one2merge/one2merge
    - go test github.com/ifosch/one2merge/one2merge
    - go vet github.com/ifosch/one2merge/one2merge
